apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: java-spring-boot
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: 'true'
    apis.apps.tanzu.vmware.com/register-api: 'true'
    app.kubernetes.io/part-of: java-spring-boot
spec:
  source:
    git:
      url: <https URL for your generated project's Git repository>
      ref:
        branch: main
  build:
    env:
    - name: BP_JVM_VERSION
      value: '17'
    - name: BP_NATIVE_IMAGE
      value: 'true'
    - name: BP_MAVEN_ACTIVE_PROFILES
      value: native
    - name: MANAGEMENT_HEALTH_PROBES_ENABLED
      value: 'true'
    - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ADD_ADDITIONAL_PATHS
      value: 'true'
    - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
      value: always
    - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH
      value: /actuator
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: '*'
    - name: MANAGEMENT_SERVER_PORT
      value: '8081'
    - name: SERVER_PORT
      value: '8080'
  env:
  - name: SPRING_CONFIG_IMPORT
    value: optional:configtree:${SERVICE_BINDING_ROOT}/config/
  - name: MANAGEMENT_HEALTH_PROBES_ENABLED
    value: 'true'
  - name: MANAGEMENT_ENDPOINT_HEALTH_PROBES_ADD_ADDITIONAL_PATHS
    value: 'true'
  - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
    value: always
  - name: MANAGEMENT_ENDPOINTS_WEB_BASE_PATH
    value: /actuator
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: '*'
  - name: MANAGEMENT_SERVER_PORT
    value: '8081'
  - name: SERVER_PORT
    value: '8080'
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      memory: 256Mi
  params:
  - name: annotations
    value:
      sidecar.opentelemetry.io/inject: 'true'
      autoscaling.knative.dev/minScale: '0'
      autoscaling.knative.dev/maxScale: '3'
      autoscaling.knative.dev/window: '60s'
      autoscaling.knative.dev/target: '20'
      autoscaling.knative.dev/metric: rps
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  - name: api_descriptor
    value:
      type: openapi
      location:
        path: /api/openapi
      owner: default/default-team
      system: default/java-spring-boot
      description: java-spring-boot API
  serviceClaims:
  - name: config
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: java-spring-boot-config
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: java-spring-boot-db
