apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: node-express
spec:
  git:
    ref:
      branch: main
    url: https://github.com/alexandreroman/awesome-tap-accelerators
    subPath: node-express
---
apiVersion: accelerator.apps.tanzu.vmware.com/v1alpha1
kind: Accelerator
metadata:
  name: spring-boot-frontend
spec:
  git:
    ref:
      branch: main
    url: https://github.com/alexandreroman/awesome-tap-accelerators
    subPath: spring-boot-frontend
