volumes:
  postgres:
    driver: local

services:
  postgres:
    image: 'postgres:15'
    environment:
    - 'POSTGRES_DB=mydatabase'
    - 'POSTGRES_PASSWORD=secret'
    - 'POSTGRES_USER=myuser'
    ports:
    - '5432:5432'
