logging:
  level:
    com.vmware.tanzu: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: false
    sampling:
      probability: 1
  otlp:
    metrics:
      export:
        enabled: false
